name: ci

on: [push]

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0

      - name: Install Fern
        run:  npm install -g fern-api

      - name: Check Fern API is valid
        run: fern check

  fern-generate-node: 
    needs: fern-check
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/node@')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v3
      
      - name: Download Fern
        run: npm install -g fern-api

      - name: Release SDKs, OpenAPI, Postman
        env:
          FERN_NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: | 
          tag=${{ github.ref_name }}
          prefix="node@"
          SDK_VERSION="${tag#$prefix}"
          fern generate --group ts-sdk --version "$SDK_VERSION" --log-level debug
    
  fern-generate-java: 
    needs: fern-check
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/java@')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v3
      
      - name: Download Fern
        run: npm install -g fern-api

      - name: Release SDKs, OpenAPI, Postman
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          FERN_MAVEN_USERNAME: ${{ secrets.FERN_MAVEN_USERNAME }}
          FERN_MAVEN_PASSWORD: ${{ secrets.FERN_MAVEN_PASSWORD }}
        run: | 
          tag=${{ github.ref_name }}
          prefix="java@"
          SDK_VERSION="${tag#$prefix}"
          fern generate --group java-sdk --version "$SDK_VERSION" --log-level debug
